apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer-deployment
  namespace: webapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
        - name: adminer
          image: adminer:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: adminer-config
          resources:
            requests:
              cpu: "20m"
            limits:
              cpu: "100m"
