apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-storage-postgres-0
  namespace: webapp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: pvc-ee193bdc-6a84-4a58-ba7c-146a040a3b00
